'use client';

import { useMemo, useState } from 'react';
import type { AnalyzedDocument } from '@/lib/types';

type Route = 'welcome'|'setup'|'dashboard'|'scan'|'analyzing'|'result'|'documents'|'document'|'tasks'|'timeline'|'settings';
type StoredDoc = AnalyzedDocument & { id:string; createdAt:string; fileUrl?:string; fileName:string; fileType:string; mode?:string; note?:string };

export default function Home(){
  const [name,setName]=useState('Sascha');
  const [route,setRoute]=useState<Route>('welcome');
  const [file,setFile]=useState<File|null>(null);
  const [fileUrl,setFileUrl]=useState('');
  const [analysis,setAnalysis]=useState<AnalyzedDocument|null>(null);
  const [mode,setMode]=useState('');
  const [note,setNote]=useState('');
  const [docs,setDocs]=useState<StoredDoc[]>([]);
  const [selected,setSelected]=useState<StoredDoc|null>(null);
  const [brain,setBrain]=useState(false);
  const [loading,setLoading]=useState(false);
  const categories=useMemo(()=>Array.from(new Set(docs.map(d=>d.category))).filter(Boolean),[docs]);
  const active=selected || (analysis ? {...analysis,id:'preview',createdAt:'gerade eben',fileUrl,fileName:file?.name||'',fileType:file?.type||'',mode,note} as StoredDoc : null);

  function chooseFile(f:File|null){ if(!f)return; setFile(f); if(fileUrl)URL.revokeObjectURL(fileUrl); setFileUrl(URL.createObjectURL(f)); }
  async function analyze(){ if(!file)return; setLoading(true); setRoute('analyzing'); const body=new FormData(); body.append('file',file); try{ const res=await fetch('/api/analyze',{method:'POST',body}); const json=await res.json(); setAnalysis(json.analysis); setMode(json.mode); setNote(json.note||''); setRoute('result'); }catch{ alert('Analyse fehlgeschlagen.'); setRoute('scan'); }finally{ setLoading(false); } }
  function saveDoc(){ if(!analysis||!file)return; const d:StoredDoc={...analysis,id:String(Date.now()),createdAt:'gerade eben',fileName:file.name,fileType:file.type,fileUrl,mode,note}; setDocs(p=>[d,...p]); setSelected(d); setBrain(false); setRoute('document'); }
  function openDoc(d:StoredDoc){ setSelected(d); setBrain(false); setRoute('document'); }
  function reset(){ setDocs([]); setSelected(null); setFile(null); setFileUrl(''); setAnalysis(null); setRoute('welcome'); }

  return <main className="app">
    <aside className="sidebar"><div className="brand"><div className="brandIcon">🧠</div><div><b>DocBrain</b><span>MVP v1</span></div></div>
      <button onClick={()=>setRoute('dashboard')}>🏠 Übersicht</button><button onClick={()=>setRoute('scan')}>📷 Scannen</button><button onClick={()=>setRoute('documents')}>📂 Dokumente</button><button onClick={()=>setRoute('tasks')}>✅ Aufgaben</button><button onClick={()=>setRoute('timeline')}>📅 Chronik</button><button onClick={()=>setRoute('settings')}>⚙️ Einstellungen</button>
      <div className="trust"><b>🔒 Originale bleiben unverändert</b><span>Ohne API-Key läuft nur der Testmodus.</span></div></aside>
    <section className="workspace">
      {route==='welcome'&&<Center><div className="panel"><div className="logo">🧠</div><p className="eyebrow">DocBrain MVP</p><h1>Dein Papierkram, ruhig geregelt.</h1><p>Erste echte Produktbasis mit Upload, API-Analyse, Ablage, Aufgaben und Chronik.</p><button className="primary" onClick={()=>setRoute('setup')}>Einrichten</button></div></Center>}
      {route==='setup'&&<Center><div className="panel"><button className="round" onClick={()=>setRoute('welcome')}>←</button><p className="eyebrow">Einrichtung</p><h1>Wie dürfen wir dich nennen?</h1><input className="input" value={name} onChange={e=>setName(e.target.value)}/><div className="setupBox"><b>Grundeinstellung</b><p>Rechnungen sofort anzeigen · Fristen 3 Tage vorher · keine Markenfarben</p></div><button className="primary" onClick={()=>setRoute('dashboard')}>Zum Dashboard</button></div></Center>}
      {route==='dashboard'&&<Screen title="DocBrain" eyebrow="Übersicht" right={<button className="round" onClick={()=>setRoute('settings')}>⚙️</button>}>{docs.length===0?<div className="statusCard"><span className="pill green">🟢 Bereit</span><h2>Noch keine Dokumente vorhanden.</h2><p>Scanne dein erstes Dokument. DocBrain analysiert es und legt es passend ab.</p><button className="primary" onClick={()=>setRoute('scan')}>📷 Erstes Dokument scannen</button></div>:<><div className="statusCard"><span className="pill green">🟢 Alles unter Kontrolle</span><h2>Du musst dich heute um nichts kümmern.</h2><p>Wir melden uns, sobald etwas deine Aufmerksamkeit braucht.</p></div><div className="stats"><button onClick={()=>setRoute('documents')}><b>{docs.length}</b><span>Dokumente</span></button><button><b>{categories.length}</b><span>Kategorien</span></button><button onClick={()=>setRoute('tasks')}><b>{docs.filter(d=>d.status!=='archived').length}</b><span>Aufgaben</span></button><button><b>100%</b><span>analysiert</span></button></div><button className="primary" onClick={()=>setRoute('scan')}>📷 Dokument hinzufügen</button><h2>Letzte Aktivität</h2><div className="list">{docs.slice(0,5).map(d=><button key={d.id} className="row" onClick={()=>openDoc(d)}>✅ {d.title}<small>{d.sender} · {d.category}</small></button>)}</div></>}</Screen>}
      {route==='scan'&&<Screen title="Dokument hinzufügen" eyebrow="Scan" back={()=>setRoute('dashboard')}><div className="scanGrid"><div className="scanStage">{!fileUrl?<div><div className="scanIcon">📄</div><h2>Foto auswählen</h2><p>Für echte Erkennung bitte ein Foto/Screenshot hochladen.</p></div>:file?.type.startsWith('image/')?<img src={fileUrl} alt="Vorschau"/>:<div className="pdfBox">📄 {file?.name}</div>}{file&&<div className="cropHint">✂️ Scan wird vorbereitet · Ränder und Lesbarkeit werden geprüft</div>}</div><div className="panel small"><input id="file" type="file" accept="image/*,.pdf" capture="environment" onChange={e=>chooseFile(e.target.files?.[0]||null)}/><label htmlFor="file" className="primary fileLabel">Foto/PDF auswählen</label><p className="muted">Bilddateien können direkt analysiert werden. PDF-OCR ist der nächste Schritt.</p><button className="primary" disabled={!file||loading} onClick={analyze}>{loading?'Analysiere ...':'Dokument analysieren'}</button></div></div></Screen>}
      {route==='analyzing'&&<Center><div className="panel centerText"><div className="pulse">🧠</div><h1>DocBrain prüft dein Dokument.</h1><p>Scan vorbereiten, Text lesen, Absender und Dokumenttyp erkennen.</p></div></Center>}
      {route==='result'&&analysis&&<Screen title="Vorschlag" eyebrow="Ergebnis" back={()=>setRoute('scan')}>{mode==='fallback'&&<div className="warning">Testmodus: Für echte Erkennung OPENAI_API_KEY setzen. {note}</div>}<div className="resultGrid"><Preview fileUrl={fileUrl} file={file}/><DocumentSummary doc={analysis} name={name}/></div><button className="primary" onClick={saveDoc}>Alles speichern</button></Screen>}
      {route==='document'&&active&&<div className="docScreen"><header className="top overlay"><button className="round" onClick={()=>setRoute('documents')}>←</button><div><p className="eyebrow">{active.category}{active.subcategory?` → ${active.subcategory}`:''}</p><h1>{active.title}</h1></div><button className="round" onClick={()=>setRoute('documents')}>📂</button></header><div className="paperCanvas"><Preview fileUrl={active.fileUrl||fileUrl} file={{type:active.fileType,name:active.fileName} as File}/></div><button className="brainButton" onClick={()=>setBrain(true)}>🧠</button>{brain&&<div className="sheetBackdrop" onClick={()=>setBrain(false)}/>} {brain&&<div className="brainSheet"><div className="handle"/><DocumentSummary doc={active} name={name} compact/><div className="actions">{active.suggestedActions.map(a=><button className="secondary" key={a}>{a}</button>)}</div></div>}</div>}
      {route==='documents'&&<Screen title="Dokumente" eyebrow="Ablage" back={()=>setRoute('dashboard')} right={<span className="pill">{docs.length}</span>}>{docs.length===0?<div className="statusCard"><h2>Noch keine Dokumente.</h2><button className="primary" onClick={()=>setRoute('scan')}>Dokument hinzufügen</button></div>:<div className="list">{docs.map(d=><button className="row" key={d.id} onClick={()=>openDoc(d)}><b>{d.title}</b><small>{d.sender} · {d.category}{d.subcategory?` → ${d.subcategory}`:''}</small></button>)}</div>}</Screen>}
      {route==='tasks'&&<Screen title="Was wirklich zählt" eyebrow="Aufgaben" back={()=>setRoute('dashboard')}>{docs.filter(d=>d.status!=='archived').length===0?<div className="statusCard"><span className="pill green">🟢 Alles erledigt</span><h2>Aktuell ist nichts offen.</h2></div>:<div className="list">{docs.filter(d=>d.status!=='archived').map(d=><button className="row" key={d.id} onClick={()=>openDoc(d)}>{d.title}<small>{d.reminderDate||d.dueDate||'Prüfen'}</small></button>)}</div>}</Screen>}
      {route==='timeline'&&<Screen title="Nachvollziehbar" eyebrow="Chronik" back={()=>setRoute('dashboard')}>{docs.length===0?<div className="statusCard"><h2>Noch keine Aktivität.</h2></div>:<div className="list">{docs.map(d=><button className="row" key={d.id} onClick={()=>openDoc(d)}>✅ {d.title} gespeichert<small>{d.createdAt} · Original unverändert</small></button>)}</div>}</Screen>}
      {route==='settings'&&<Screen title="Persönlich" eyebrow="Einstellungen" back={()=>setRoute('dashboard')}><div className="list"><div className="setting"><b>👤 Name</b><span>{name}</span></div><div className="setting"><b>🎨 Farben</b><span>nur Status, keine Markenfarben</span></div><div className="setting"><b>🔒 Originale</b><span>bleiben unverändert</span></div><button className="secondary danger" onClick={reset}>Testdaten löschen</button></div></Screen>}
      <nav className="bottomNav"><button onClick={()=>setRoute('dashboard')}>🏠<span>Home</span></button><button onClick={()=>setRoute('documents')}>📂<span>Dokumente</span></button><button className="plus" onClick={()=>setRoute('scan')}>＋</button><button onClick={()=>setRoute('tasks')}>✅<span>Aufgaben</span></button><button onClick={()=>setRoute('timeline')}>📅<span>Chronik</span></button></nav>
    </section></main>;
}
function Center({children}:{children:React.ReactNode}){return <div className="center">{children}</div>}
function Screen({title,eyebrow,children,back,right}:{title:string;eyebrow:string;children:React.ReactNode;back?:()=>void;right?:React.ReactNode}){return <div className="screen"><header className="top">{back?<button className="round" onClick={back}>←</button>:<span/>}<div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{right||<span/>}</header>{children}</div>}
function Preview({fileUrl,file}:{fileUrl?:string;file:File|{type?:string;name?:string}|null}){if(fileUrl&&file?.type?.startsWith('image/'))return <div className="docPreview"><img src={fileUrl} alt="Original"/></div>;return <div className="docPreview"><div className="paper"><h2>{file?.name||'Dokument'}</h2><p>Originalansicht. Das Dokument bleibt unverändert.</p></div></div>}
function DocumentSummary({doc,name,compact=false}:{doc:AnalyzedDocument;name:string;compact?:boolean}){const rows:[string,string|null|undefined][]=[['🏢 Absender',doc.sender],['📄 Dokument',doc.title],['📂 Ablage',doc.subcategory?`${doc.category} → ${doc.subcategory}`:doc.category],['🏷️ Typ',doc.documentType],['📝 Inhalt',doc.summary]]; if(doc.amount)rows.push(['💰 Betrag',doc.amount]); if(doc.dueDate)rows.push(['📅 Frist',doc.dueDate]); if(doc.reminderDate)rows.push(['🔔 Erinnerung',doc.reminderDate]); rows.push(['🟢 Status',doc.status==='archived'?'Archiviert':doc.status==='open'?'Offen':'Bitte prüfen']);return <div className={compact?'':'summaryCard'}><p className="eyebrow">DocBrain Übersicht</p><h2>{doc.needsClarification?`${name}, bitte kurz prüfen.`:`${name}, ich habe „${doc.title}“ erkannt.`}</h2>{rows.map(([l,v])=><div className="field" key={l}><span>{l}</span><b>{v}</b></div>)}{doc.confidence<0.9&&<p className="note">DocBrain ist hier noch nicht sicher genug. In der finalen Version wird nur bei echter Unsicherheit nachgefragt.</p>}</div>}
